'use client'
import { Metadata } from 'next'
import { ReactLenis } from "lenis/react";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['300', '400', '500', '600', '700', '800', '900']
});

export const Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-dark-blue overflow-x-hidden`}
      >
        <Navbar />
        <ReactLenis root>
          {children}
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
